openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: local dev servers
  - url: https://task-api-kwr6.onrender.com
    description: production server on render
tags:
  - name: tasks
    description: task related endpoints
paths:
  /tasks:
    /tasks:
      get:
        summary: List all tasks
        tags:
          - tasks
        parameters:
          - name: completed
            in: query
            required: false
            description: Filter tasks by completion status
            schema:
              type: boolean
              example: true
          - name: limit
            in: query
            required: false
            description: Maximum number of tasks returned
            schema:
              type: integer
              example: 10
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: ../components/task.yaml#/Task
      post:
        summary: Create a new task
        tags:
          - tasks
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: ../components/task.yaml#/NewTask
        responses:
          '201':
            description: Task created successfully
            content:
              application/json:
                schema:
                  $ref: ../components/task.yaml#/Task
          '400':
            description: Validation error
            content:
              application/json:
                $ref: ../components/validation-error.yaml#/ValidationError
    /tasks/{id}:
      get:
        summary: Get a task by ID
        tags:
          - tasks
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
            description: Numeric ID of the task
        responses:
          '200':
            description: Task found
            content:
              application/json:
                schema:
                  $ref: ../components/task.yaml#/Task
          '400':
            description: Validation error
            content:
              application/json:
                schema:
                  $ref: ../components/validation-error.yaml#/ValidationError
          '404':
            description: Task not found
            content:
              application/json:
                schema:
                  $ref: ../components/not-found-error.yaml#/NotFoundError
components: {}
