openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: tasks
    description: task related endpoints
paths:
  /tasks:
    get:
      summary: list all /tasks
      tags:
        - tasks
      parameters:
        - name: completed
          in: query
          required: false
          description: filter tasks by completion status
          schema:
            type: booleam
            example: true
        - name: limit
          in: query
          required: false
          description: maximum number of tasks returned
          schema:
            type: integer
            example: 10
      responses:
        ' 200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $REF: ../components/schemas/Task.yaml
    post:
      summary: Create a new task
      tags:
        - tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $REF: ../components/schemas/Task.yaml
      responses:
        '201':
          description: task created successfully
          content:
            application/json:
              schema:
                $REF: ../components/schemas/Task.yaml
        '400':
          $REF: ../components/responses/badrequest.yaml
components: {}
